### ISSUE TITLE
Date de sortie modifiée

### ISSUE THREAD

**Issue by florealcab** [berrydamien/kaamelott-motd#2]
La date de sortie de Kaamelott est avancée au 29 juillet 2020, il faudrait donc mettre à jour le compte à rebours en conséquence...

Bon en vrai c'est juste pour le plaisir de mettre une issue sur ce projet... capital !! ;-)))

**Comment by berrydamien** [comment]
https://twitter.com/AAstierOff/status/1258419474925072384?s=19&fbclid=IwAR3SuPC9hYUiJpR19JjIHe9Ovz556uDZRC0Gm-Ox1tO8BI074_XRdCs7ISw

La sortie de #KaamelottPremierVolet reportée au 25 novembre 2020.
